spring:
  config:
    import:
      - classpath:/yml/application-secret.yml
      - classpath:/yml/application-local.yml
      - classpath:/yml/application-dev.yml

  profiles:
    active: local # default
    group:
      local:
        - secret # local + secret
      dev:
        - secret